name: Flutter

on:
  push:
    branches:
      - main

jobs:
  flutter_test:
    name: Test, analyze and build Flutter app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup latest Java 21 Version.
        uses: actions/setup-java@v1
        with:
          java-version: "21.x"

      - name: Set up Flutter.
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install Dependencies.
        run: flutter pub get

      - name: Create empty .env file
        run: echo "Creating .env file" && touch assets/.env

      - name: Analyze structure and errors in code.
        run: flutter analyze

      - name: Run test files.
        run: flutter test

      - name: Build Android App
        run: flutter build apk --release

      - name: Upload Android APK
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Set up macOS for iOS build
        if: runner.os == 'macOS'
        run: |
          sudo gem install cocoapods
          sudo xcode-select --switch /Applications/Xcode_15.0.app

      - name: Build iOS App
        if: runner.os == 'macOS'
        run: flutter build ios --release

      - name: Upload iOS IPA
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v2
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
